name: Autonomous deployment
run-name: Website Deployment
on:
  push:
    branches:
      - master
jobs:

# Testing the site configuration with astro check >> https://docs.astro.build/de/reference/cli-reference/#astro-check

    website-check:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Branch
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '19'
            cache: 'npm'
        - name: Installing Astro
          run: npm install astro
        - name: Testing Website
          run: npm run astro check

# Build the website and cache it >> https://docs.astro.build/de/reference/cli-reference/#astro-build

    website-build:
      runs-on: ubuntu-latest
      needs: website-check
      steps:
        - name: Checkout Branch
          uses: actions/checkout@v3
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: '19'
            cache: 'npm'
        - name: Installing Astro
          run: npm install astro
        - name: Building Website
          run: npm run build
        - name: Write Website to Cache
          uses: actions/cache/save@v3
          env:
            cache-name: website-build
          with:
            path: ./dist
            key: build-cache
          
# Deploy the Website (Won't do anything)
        
    website-deployment:
      runs-on: ubuntu-latest
      needs: website-build
      steps:
        - name: Write Website to Cache
          uses: actions/cache/restore@v3
          env:
             cache-name: website-build
          with:
             path: ./dist
             key: build-cache
        - run: ls -l
